# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.9"

services:
  auto-gpt:
    depends_on:
      - redis
    build: ./
    env_file:
      - .env
    volumes:
      - "./autogpt:/app"
      - ".env:/app/.env"
    profiles: ["exclude-from-up"]
    networks:
      - default

  redis:
    image: "redis/redis-stack-server:latest"
    volumes:
      - "./redis:/data"
    env_file:
      - .env
    profiles: ["exclude-from-up"]
    expose:
      - 6379
    networks:
      - default

networks:
  default:
      name: "autogpt_default"
